### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by dmendat** [SpiNNakerManchester/sPyNNakerExtraModelsPlugin#6]
When installing on Ubuntu (sudo python setup.py develop --no-deps) every line works until I hit the following error:

error: package directory 'spynnaker_extra_pynn_models/neural-models' does not exist

**Comment by chanokin** [comment]
I tried to install but got this error:

error: package directory 'spynnaker_extra_pynn_models/neural_properties' does not exist

**Comment by rowleya** [comment]
This is a transient error that has been fixed.
